version: "3.8"

services:
  # Mimir Backend Storage (S3)
  minio-mimir:
    image: minio/minio:RELEASE.2023-06-19T19-52-50Z
    container_name: lgtm-minio-mimir
    hostname: minio-mimir
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/mimir && minio server --quiet /data"]
    env_file:
      - ./env/minio-mimir.env
    volumes:
      - minio-mimir-data:/data

  # Prometheus-compatible Metrics Backend
  mimir:
    image: grafana/mimir:2.9.0
    container_name: lgtm-mimir
    hostname: mimir
    command: [ "-config.file=/etc/mimir.yaml" ]
    volumes:
      - ./config/mimir.yaml:/etc/mimir.yaml
      - ./config/mimir-alertmanager.yaml:/etc/mimir-alertmanager.yaml
      - mimir-data:/data
    depends_on:
      - minio-mimir

  # Loki Backend Storage (S3)
  minio-loki:
    image: minio/minio:RELEASE.2023-06-19T19-52-50Z
    container_name: lgtm-minio-loki
    hostname: minio-loki
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/loki && minio server --quiet /data"]
    env_file:
      - ./env/minio-loki.env
    volumes:
      - minio-loki-data:/data

  # Logs Backend
  loki:
    image: grafana/loki:2.8.2
    container_name: lgtm-loki
    hostname: loki
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki.yaml:/etc/loki/config.yaml
    command: ["-config.file=/etc/loki/config.yaml"]
    depends_on:
      - minio-loki

  grafana:
    image: grafana/grafana:10.0.0
    container_name: lgtm-grafana
    hostname: grafana
    ports:
      - "8080:3000"
    env_file:
      - ./env/grafana.env
    volumes:
      - ./config/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
      - ./dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    depends_on:
      - mimir
      - loki

  test-agent:
    image: grafana/agent:v0.34.2
    container_name: lgtm-test-agent
    hostname: test-agent
    volumes:
      - test-agent-data:/etc/agent/data
      - ./config/agent.yaml:/etc/agent/agent.yaml
    depends_on:
      - mimir

  test-promtail:
    image: grafana/promtail:2.8.2
    container_name: test-promtail
    hostname: test-promtail
    volumes:
      - ./config/promtail.yaml:/etc/promtail/config.yaml
    command: ["-config.file=/etc/promtail/config.yaml"]
    depends_on:
      - loki

volumes:
  minio-mimir-data:
    name: lgtm-minio-mimir-data
    external: false
  minio-loki-data:
    name: lgtm-minio-loki-data
    external: false
  mimir-data:
    name: lgtm-mimir-data
    external: false
  grafana-data:
    name: lgtm-grafana-data
    external: false
  test-agent-data:
    name: lgtm-test-agent-data
    external: false
